### PR TITLE
Update preprints posted up until 2021-02-28

### PR DESCRIPTION
**Pull request by bmkramer**
Regular update - preprints posted up until 2021-02-28
Added some general remarks on deduplication in Readme.

### CODE REVIEW

**Comment by nicholasmfraser** [comment]
Thanks, merged!

**Comment by bmkramer** [comment]
Super! Still intend to try switching to incremental updates :-)

Op di 9 mrt. 2021 om 15:37 schreef Nicholas Fraser ***@***.***

**Comment by nicholasmfraser** [comment]
Shall we try the incremental updates for the next version? How do you want to handle that? From my side I think monthly updates are now reasonable, so we could update at the end of March, unless you prefer a shorter interval.

**Comment by bmkramer** [comment]
Yes, I had hoped (still hope...) to test the incremental update this week for the data up until March 14, so with a 2 week interval since the last full update. If that works well, we can implement it at either a montly or twice montly interval.

**Pull request merged**
